[package]
name = "rustworkx-core-sql-serialization"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.6", features = ["sqlite"] }
rustworkx-core = "0.15.1"
diesel_migrations = "2.2.0"

[[bin]]
name = "rustworkx-core-sql-serialization-bin"
path = "src/main.rs"
